UFF-029 - Implementar escolha da próxima jogada do computador
lucasfauster/xadruff-backend pull request #7
Opened 2022-05-03 20:42 UTC by lucasfauster

2022-05-03 20:49 UTC, luamz approved these changes

2022-05-03 20:59 UTC, igorcruzf requested changes

2022-05-03 20:59 UTC, igorcruzf commented on src/main/kotlin/com/uff/br/xadruffbackend/model/Minimax.kt
> +package com.uff.br.xadruffbackend.model
Minimax por ser um algoritmo era pra estar em uma camada de serviço e não estar dentro do pacote de Model (onde fica os DTOs/entities)

2022-05-03 20:59 UTC, igorcruzf commented on src/main/kotlin/com/uff/br/xadruffbackend/model/Minimax.kt
> +package com.uff.br.xadruffbackend.model
Por ser algo de ia, eu acho que poderia ter um módulo de AI (em ingles), dai uma classe de serviço AIService ou algo do tipo que seria o que o back chamaria para fazer o cálculo e ter ou um serviço para o algoritmo ou isso ser parte do serviço de IA, apenas sugestões no caso

2022-05-03 20:59 UTC, igorcruzf commented on src/main/kotlin/com/uff/br/xadruffbackend/model/Minimax.kt
> +class Piece(value: Char) {
Colocar separado dentro de model e colocar como data class pra seguir um padrão

2022-05-03 20:59 UTC, igorcruzf commented on src/main/kotlin/com/uff/br/xadruffbackend/model/Minimax.kt
> +    fun getColor() = this.value.isUpperCase() // upperCase = Branco = True
Tem um enum de cor que poderia ser utilizado nessa função

2022-05-03 20:59 UTC, igorcruzf commented on src/main/kotlin/com/uff/br/xadruffbackend/model/Minimax.kt
> +    private val piecePositionWeights =mapOf(
Acho que podia ter uma classe Weights separada com esses maps de forma estatica como companion object, pra ajudar na leitura do arquivo

2022-05-03 20:59 UTC, igorcruzf commented on src/main/kotlin/com/uff/br/xadruffbackend/model/Minimax.kt
> +        if(depth == 0) return -evaluate(boardMock)
má pratica colocar ifs na mesma linha mesmo que seja apenas uma instrução

2022-05-03 20:59 UTC, igorcruzf commented on src/main/kotlin/com/uff/br/xadruffbackend/model/Minimax.kt
> +                if (beta <= alpha) return bestMoveValue
Mesma coisa aqui do if na mesma linha, além disso será que n tem um nome melhor pra alpha e beta? fiquei um pouco confuso sobre oq eles representam

2022-05-03 20:59 UTC, igorcruzf commented on src/main/kotlin/com/uff/br/xadruffbackend/model/Minimax.kt
> +            for(move in boardMock.legalMoves){
isso aqui não poderia ser refatorado para uma função? parece repetido da linha 153

2022-05-03 21:00 UTC, igorcruzf commented on src/main/kotlin/com/uff/br/xadruffbackend/model/Minimax.kt
> +                if (beta <= alpha) return bestMoveValue
if na mesma linha dnv!

2022-05-03 21:01 UTC, igorcruzf requested changes

2022-05-03 21:01 UTC, igorcruzf commented on src/main/kotlin/com/uff/br/xadruffbackend/model/Minimax.kt
> +                    if (playerColor == pieceColor) piecePositionWeights.getValue(piece)[i][j] else piecePositionWeights.getValue(piece).reversed()[i][j]
if na mesma linha dnv!

2022-05-03 21:01 UTC, igorcruzf commented on src/main/kotlin/com/uff/br/xadruffbackend/model/Minimax.kt
> +                weight = if (playerColor == pieceColor) weight + pieceWeightValue else weight - pieceWeightValue
if na mesma linha dnv!

2022-05-03 21:07 UTC, igorcruzf commented on src/main/kotlin/com/uff/br/xadruffbackend/model/Minimax.kt
> +        if(depth == 0) return -evaluate(boardMock)
https://stackoverflow.com/questions/691476/are-singleline-if-statements-or-if-statements-without-braces-bad-practice << explicada rapida pelo stackoverflow

2022-05-05 17:22 UTC, igorcruzf approved these changes

2022-05-05 20:01 UTC, merged